# Generated by Django 4.0.2 on 2022-02-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='questionanswer',
        ),
    ]
