# Generated by Django 4.0.2 on 2022-02-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_question_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question',
            new_name='ques',
        ),
    ]
