# Generated by Django 4.0.2 on 2022-02-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_question_questionanswer_ques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='name',
            new_name='university_name',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='university',
        ),
    ]
