# Generated by Django 4.0.2 on 2022-02-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_name_subject_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='university_select',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.university'),
            preserve_default=False,
        ),
    ]
