# Generated by Django 4.0.2 on 2022-02-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_questionanswer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
