# Generated by Django 4.0.2 on 2022-02-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_questionanswer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
