# Generated by Django 4.0.2 on 2022-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_questionanswer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='timesAsked',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
