# Generated by Django 4.0.2 on 2022-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_questionanswer_timesasked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='timesAsked',
            field=models.IntegerField(default=0),
        ),
    ]
