# Generated by Django 4.0.2 on 2022-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_questionanswer_important_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='timesAsked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
