# Generated by Django 4.0.2 on 2022-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_questionanswer_timesasked'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='semester',
            field=models.CharField(default='semester 1', max_length=10),
            preserve_default=False,
        ),
    ]
