# Generated by Django 4.0.2 on 2022-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_questionanswer_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='semester',
            field=models.CharField(max_length=25),
        ),
    ]
