# Generated by Django 4.0.2 on 2022-02-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedback_m',
        ),
    ]
