# Generated by Django 4.0.2 on 2022-02-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_feedback_feedback_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
