# Generated by Django 4.0.2 on 2022-03-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
