# Generated by Django 4.0.2 on 2022-03-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
